### ISSUE TITLE
BIGNUMERIC values

### ISSUE THREAD

**Issue by mdubeau19** [r-dbi/bigrquery#520] opened 2023-01-20 15:24 UTC
I am currently trying to bring in tables that have fields that use bignumeric and getting an error message that bignumeric is not currently supported. Is there a fix or work around for this issue? 

Thanks.

**Comment by hadley** [comment] 2023-11-02 22:15
Can you please provide a minimal reprex (*repr*oducible *ex*ample)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you! If you've never heard of a reprex before, start by reading [about the reprex package](https://reprex.tidyverse.org/index.html), including the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment] 2023-11-03 21:43
Looks like a duplicate of #435

**Closed by hadley** 2023-11-03 21:43 UTC
Labels: reprex
