### ISSUE TITLE
Internal error when using verbs

### ISSUE THREAD

**Issue by mapinas** [r-dbi/bigrquery#358] opened 2019-11-09 19:16 UTC
I can successfully connect and download data from Google BigQuery using the bigrquery package.

`test <- dbTesting %>%
  tbl("px_testing7") %>% 
  collect()`

However, as soon as I add a verb (mutate, select, groupby+summarise...), I receive the following error message "Error: An internal error occurred and the request could not be completed. [internalError]". Examples:

`test <- dbTesting %>%
  tbl("px_testing7") %>% 
  mutate(newVar="newVal") %>%
  collect()`

Or

`test <- dbTesting %>%
  tbl("px_testing7") %>% 
  select(country_code) %>%
  collect()`

Using the most recent version of dbplyr and bigrquery installed through devtools in R.

**Comment by hadley** [comment] 2020-05-01 16:34
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment] 2020-10-01 19:58
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2020-10-01 19:58 UTC
Labels: reprex
