### ISSUE TITLE
Running behind a proxy

### ISSUE THREAD

**Issue by arvhug** [r-dbi/bigrquery#348] opened 2019-09-20 00:50 UTC
Hi, 
I was trying to run bigrquery behind a corporate proxy and was having the issue where the file 'bq-xxxx.json' would not download causing bq_parse_files to obviously fail.

I fixed this issue by modifying the two functions; bq_download_pages() and bq_download_page_handle() 

```r
bq_download_pages<-
  
  function (x, page_info, max_connections = 6L, quiet = NA) 
{
  x <- as_bq_table(x)
  assert_that(is.list(page_info))
  n_pages <- page_info$n_pages
  if (n_pages == 0) {
    return(character())
  }
  paths <- tempfile(rep("bq-", n_pages), fileext = ".json")
  pool <- curl::new_pool(host_con = max_connections)
  progress <- bigrquery:::bq_progress("Downloading data [:bar] :percent ETA: :eta", 
                          total = n_pages, quiet = quiet)
  for (i in seq_len(n_pages)) {
    handle <- bigrquery:::bq_download_page_handle(x, begin = page_info$begin[i], 
                                      end = page_info$end[i])
    curl::multi_add(handle, done =bigrquery:::bq_download_callback(i, 
                                                        paths[[i]], progress), pool = pool)
  }
  curl::multi_run(pool = pool)
  paths
}
```
Above I added ::: to access unexported objects

```r
bq_download_page_handle<-function (x, begin = 0L, end = begin + 10000) 
{
  ### Arv editing the curl so we can use a proxy 
  base_url <- "https://www.googleapis.com/bigquery/v2/"
  x <- as_bq_table(x)
  assert_that(is.numeric(begin), length(begin) == 1)
  assert_that(is.numeric(end), length(end) == 1)
  query <- list(startIndex = begin, maxResults = end - begin)
  url <- paste0(base_url, bigrquery:::bq_path(x$project, dataset = x$dataset, 
                                  table = x$table, data = ""))
  url <- httr::modify_url(url, query = bigrquery:::prepare_bq_query(query))
  proxy = ie_get_proxy_for_url(url) ### getting proxy config
  if (bq_has_token()) {
    token <- bigrquery:::.auth$get_cred()
    signed <- token$sign("GET", url)
    url <- signed$url
    headers <- signed$headers
  }
  else {
    headers <- list()
  }
  h <- curl::new_handle(url = url,proxy=proxy) ### adding proxy
  curl::handle_setopt(h, useragent = bigrquery:::bq_ua())
  curl::handle_setheaders(h, .list = headers)
  h
}
```
Above I added the proxy as well as :::  and had to specify the base_url

This was the only approach I could use to get the file downloading behind a proxy, having tried set_config and Sys.setenv to no avail.

Is this a bug or is there a better way to configure bigrquery behind a proxy?

**Comment by hadley** [comment] 2020-05-01 16:31
Hmmmm, the problem is that this is the only pathway that doesn't use httr, which already has existing mechanisms to handle this issue. Maybe we can port some of the httr defaults to this code path?

**Comment by hadley** [comment] 2023-11-08 17:50
Closing this since no further correspondence for 3 years, and presumably you've worked around the problem by now. Sorry for not getting back to you sooner!

**Closed by hadley** 2023-11-08 17:50 UTC
Labels: feature, download :arrow_down:
