### ISSUE TITLE
Proper "tidy" way to create a BQ table and upload data.

### ISSUE THREAD

**Issue by abalter** [r-dbi/bigrquery#422] opened 2020-11-13 09:02 UTC
I'm struggling with what would be the "right" way to create a table on BQ and upload data into it using `bigrquery`.

This is the `DBI` way to do it:

``` r
library(DBI)
library(dplyr, warn.conflicts = FALSE)
library(bigrquery)

bq_deauth()
bq_auth(email="ariel.balter@gmail.com")

dataset = bq_dataset("elite-magpie-257717", "test_dataset")

if (bq_dataset_exists(dataset))
{
  bq_dataset_delete(dataset, delete_contents = T)
}
bq_dataset_create(dataset)
#> <bq_dataset> elite-magpie-257717.test_dataset

conn = dbConnect(
  bigrquery::bigquery(),
  project = "elite-magpie-257717",
  dataset = "test_dataset",
  KeyFilePath = "google_service_key.json",
  OAuthMechanism = 0
)

dbWriteTable(conn, "mtcars", mtcars, overwrite=T)

dbListTables(conn)
#> [1] "mtcars"
```

<sup>Created on 2020-11-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This is my attempt at using `bigrquery`. It is clumsy and throws an error about schema not being provided, although there is nothing about that in the documentation.

``` r
library(DBI)
library(dplyr, warn.conflicts = FALSE)
library(bigrquery)

bq_deauth()
bq_auth(email="ariel.balter@gmail.com")


dataset = bq_dataset("elite-magpie-257717", "test_dataset")

if (bq_dataset_exists(dataset))
{
  bq_dataset_delete(dataset, delete_contents = T)
}
bq_dataset_create(dataset)
#> <bq_dataset> elite-magpie-257717.test_dataset

mtcars_tbl = bq_table(dataset$project, dataset$dataset, "mtcars")

if (bq_table_exists(mtcars_tbl))
{
  bq_table_delete(mtcars_tbl)
}
bq_table_create(mtcars_tbl)
#> <bq_table> elite-magpie-257717.test_dataset.mtcars

bq_table_upload(x = mtcars_tbl, values = mtcars)
#> Error: No schema specified on job or table. [invalid]
```

<sup>Created on 2020-11-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment] 2023-11-03 13:35
Looks like a duplicate of #465

**Closed by hadley** 2023-11-03 13:35 UTC
