### ISSUE TITLE
Issue with R oath Verification

### ISSUE THREAD

**Issue by vivshume** [r-dbi/bigrquery#194] opened 2017-12-10 12:12 UTC
Hi , 
I am facing issue with R Oath verification.When I am trying to  run the query, It is going on the browser and says "Error: invalid_request". How to fix it ?

**Comment by minimaxir** [comment] 2017-12-14 21:32
Hitting this issue as well.

```
Error: invalid_request

Missing required parameter: redirect_uri
```

**Comment by j450h1** [comment] 2018-01-05 20:06
There is a workaround for this, run this before authenticating/making a call:

```options("httr_oob_default" = TRUE)```

See issue [182](https://github.com/r-dbi/bigrquery/issues/182) for more details.

**Comment by hadley** [comment] 2018-03-28 22:17
Duplicate of #182

**Closed** 2018-03-28 22:16 UTC
