### ISSUE TITLE
Bigquery Failed to Parse bq_parse_files with bq_table_download?

### ISSUE THREAD

**Issue by 3Mcolab** [r-dbi/bigrquery#464] opened 2021-10-13 02:21 UTC
I have a bigquery some table. bq_table_download functions works for most of the table (even with 6,600,000 rows), however, it shows failed to parse errors with 1 table (27 columns and 1,600,300 rows).

```
bigrquery::bq_auth()
sql_query=paste0("select * from `project_id.dataset.table_name`")
bq_table_ext=bq_table_download(bq_project_query(project_id, sql_query))
```
I am having the following errors:
```
Error in bq_parse_files(schema_path, c(path_first_chunk, chunk_plan$dat$path),  : 
  Failed to parse '/tmp/Rtmpjd5eQN/bq-download-8650ad590.json'
Calls: ... ..table_some -> bq_table_download -> bq_parse_files
In addition: Warning messages:
1: In writeBin(result$content, con) : problem writing to connection
2: In writeBin(result$content, con) : problem writing to connection
Execution halted
```

In order to address this issues, I have use the different solutions like below and nothing works:
```
options(scipen = 20)
```
I have varyied page size from 100 to 5000 and adding/removing max_connections to bq_download_table functions as well.
```
check_table=bq_table_download(bq_project_query(project_id, sql_query),page_size=100,max_connection=1)
```
Any suggestion? What might be the issues?

**Comment by jennybc** [comment] 2021-10-13 04:38
I really have no idea, but it smells like a problem that could easily be a specific row or column or specific intersection of row and column. So a "bisect" mentality seems like a fruitful troubleshooting approach. I'm just speaking from a hunch.

**Comment by meystingray** [comment] 2021-10-20 15:03
I'm getting the same error, but with this message: 

```
Error in bq_parse_files(schema_path, page_paths, n = page_info$n_rows,  :                                    
  embedded nul in string: 'MySQL Workbench 8.0 CE Installer Information\0\0'
```

Going to the data table in BigQuery, I can see that it's a result of this text:   "MySQL Workbench 8.0 CE Installer Information��"

Specifically, the question mark within a diamond symbol.   Hope that's helpful...

**Comment by guoshuyu17** [comment] 2021-12-03 17:10
I had the same issue and figure out it caused by my low disk space. The issue resolved by having more disk space. Hope it also work for you.

**Closed** 2023-11-03 13:01 UTC
