### ISSUE TITLE
true values convert to FALSE when results are returned to R as tibble

### ISSUE THREAD

**Issue by dan-booth** [r-dbi/bigrquery#242] opened 2018-04-24 05:39 UTC
Hey I've noticed while playing around with `v0.4.1.9000` that `true` values in query results seem to be getting converted to `FALSE` when returned to R as a tibble.

I'm having trouble getting a `reprex()` to work but I will explain in detail below how to replicate.

## Ground truth

First here's the query I've been playing around with:

```r
sql <- "SELECT repository.has_downloads, COUNT(*) AS n FROM `publicdata.samples.github_nested` GROUP BY repository.has_downloads"
```

Querying in the BigQuery web UI and via `bq` command returns the ground truth results:

```r
system2('bq', glue::glue("query --use_legacy_sql=false '{sql}'"))

#> +---------------+---------+
#> | has_downloads |    n    |
#> +---------------+---------+
#> |         false |   62368 |
#> |          true | 2222838 |
#> |          NULL |  256433 |
#> +---------------+---------+
```

## Problems

Now when I run this query via the **Low-level API** and **DBI interfaces** I see unexpected behaviour where these `true` values become `FALSE`. Since this query is on a nested field (`repository`) I don't think I can try the **dplyr** interface, but I have another example below where the problem also exists.

### Low-level API

Here's how to replicate the problem when using the Low-level API:

```r
library(bigrquery)
billing <- bq_test_project()

tb <- bq_project_query(billing, sql)
#> Complete
#> Billed: 0 B

bq_table_download(tb, max_results = 10)
#> Downloading 3 rows in 1 pages.
#> # A tibble: 3 x 2                                                                                          
#>   has_downloads       n
#>   <lgl>           <int>
#> 1 FALSE           62368
#> 2 FALSE         2222838
#> 3 NA             256433
```

Note the **TWO FALSE values**. Unusual. I don't know enough C++ to try work out what is happening sorry.

### DBI

Problem also exists in DBI:

```r
library(DBI)
con <- dbConnect(
  bigrquery::bigquery(),
  project = "publicdata",
  dataset = "samples",
  billing = billing
)

res <- dbGetQuery(con, sql)
#> Complete
#> Billed: 0 B
#> Downloading 3 rows in 1 pages.

res
#> # A tibble: 3 x 2
#>   has_downloads       n
#>   <lgl>           <int>
#> 1 FALSE           62368
#> 2 FALSE         2222838
#> 3 NA             256433
```

### dplyr

Here's another query that results in similar issues when using `dplyr`:

```r
library(dplyr)
natality <- tbl(con, "bigquery-public-data.samples.natality")

natality %>% 
  count(cigarette_use)

#> Complete
#> Billed: 14.68 MB
#> Downloading 3 rows in 1 pages.
#> # Source:   lazy query [?? x 2]
#> # Database: BigQueryConnection
#>   cigarette_use         n
#>   <lgl>             <int>
#> 1 FALSE           1426713
#> 2 NA            123796721
#> 3 FALSE          12603329
```
## My sessionInfo()

Here's my `sessionInfo()`:

```r
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.7.4          DBI_0.8              bigrquery_0.4.1.9000

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16      prettyunits_1.0.2 dbplyr_1.2.1      utf8_1.1.3        crayon_1.3.4     
 [6] assertthat_0.2.0  R6_2.2.2          jsonlite_1.5      magrittr_1.5      pillar_1.2.1     
[11] httr_1.3.1        cli_1.0.0         rlang_0.2.0       progress_1.1.2    curl_3.2         
[16] rstudioapi_0.7    bindrcpp_0.2.2    tools_3.4.3       glue_1.2.0        yaml_2.1.18      
[21] compiler_3.4.3    pkgconfig_2.0.1   bindr_0.1.1       tibble_1.4.2
```

I hope this helps!

Dan

**Comment by hadley** [comment] 2018-04-24 13:33
Duplicate of #234 and should be fixed once you install the latest dev version

**Closed by hadley** 2018-04-24 13:33 UTC
