### ISSUE TITLE
bq_auth() default scopes untenable on Cloud AI Platform

### ISSUE THREAD

**Issue by htappen** [r-dbi/bigrquery#390] opened 2020-06-06 00:31 UTC
bq_auth includes "https://www.googleapis.com/auth/cloud-platform" in its default scopes. That doesn't work in any cases where the VM lacks access to Google Compute Engine APIs. This will happen whenever, for security purposes, including on Cloud AI Platform training. Suggestion -- only require https://www.googleapis.com/auth/bigquery

**Comment by jennybc** [comment] 2020-06-06 19:49
This is already being tracked in https://github.com/r-lib/gargle/issues/138 where I am trying to motivate someone to provide me detailed debugging info. If you could weigh in with that sort of info, on that issue, it would be very helpful.

**Comment by htappen** [comment] 2020-06-06 21:19
I followed the instructions in https://github.com/r-lib/gargle/issues/130#issuecomment-623017017

Specifically, I ran this command from bash:
```bash
Rscript -e "remotes::install_github('r-lib/gargle#139'); library('gargle'); options(gargle_quiet = FALSE); library('bigrquery'); bq_auth()"
```

That gave me this output:
```
trying token_fetch()
trying credentials_service_account()
Error: Argument 'txt' must be a JSON string, URL or file.
trying credentials_app_default()
trying credentials_gce()
Requesting GCE metadata from: http://metadata.google.internal/computeMetadata/v1/
Requesting GCE metadata from: http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/scopes
Error in credentials_gce(): `scopes` are unacceptable
Acceptable scopes: 
* https://www.googleapis.com/auth/devstorage.read_write
* https://www.googleapis.com/auth/logging.read
* https://www.googleapis.com/auth/logging.write
* https://www.googleapis.com/auth/monitoring.write
* https://www.googleapis.com/auth/pubsub
* https://www.googleapis.com/auth/dataaccessauditlogging
* https://www.googleapis.com/auth/datastore
* https://www.googleapis.com/auth/cloud.ml.engine.internal
* https://www.googleapis.com/auth/cloudkms
* https://www.googleapis.com/auth/bigtable.data
* https://www.googleapis.com/auth/bigquery
* https://www.googleapis.com/auth/cloud-platform.read-only
Actual scopes: 
* https://www.googleapis.com/auth/bigquery
* https://www.googleapis.com/auth/cloud-platform
trying credentials_byo_oauth()
Error: inherits(token, "Token2.0") is not TRUE
trying credentials_user_oauth2()
Gargle2.0 initialize
attempt from: bigrquery
adding 'userinfo.email' scope
loading token from the cache
no matching token in the cache
initiating new token
Error: OAuth2 flow requires an interactive session
Error: Can't get Google credentials.
Are you running bigrquery in a non-interactive session? Consider:
  * Call `bq_auth()` directly with all necessary specifics.
Execution halted
```

I'm certain the problem is that `https://www.googleapis.com/auth/cloud-platform` is missing from the "Acceptable Scopes". Instead, we have `https://www.googleapis.com/auth/cloud-platform.read-only`. The problem is here: https://github.com/r-dbi/bigrquery/blob/master/R/bq-auth.R#L50

```R
bq_auth <- function(email = gargle::gargle_oauth_email(),
                    path = NULL,
                    scopes = c(
                      "https://www.googleapis.com/auth/bigquery",
                      "https://www.googleapis.com/auth/cloud-platform"
                    ),
...
```
A few possible resolutions:
1. Make bq_auth just not ask for the cloud-platform scope.
2. Make bq_auth ask for cloud-platform.readonly scope. In that case, you'll need to make `gargle::credentials_gce` succeed even if the .readonly scope is requested by full write is available. You could probably do this by removing .readonly from the requested scopes before you do the string match in this line: https://github.com/r-lib/gargle/blob/master/R/credentials_gce.R#L31
3. Make bq_auth or gargle have a graceful fallback to cloud-platform.readonly (or, really, any other readonly scope). E.g. you could introduce a new option `requires_edit = FALSE` which when `TRUE` makes gargle fail if the scopes don't EXACTLY match, but when `FALSE` makes gargle still ask for the `readonly` scope if it can find it.

**Comment by jennybc** [comment] 2020-06-06 23:10
Thanks @htappen, your debugging info is helpful.

You should be able to succeed already by explicitly calling `bq_auth(scopes = "https://www.googleapis.com/auth/bigquery")`. Can you confirm that it is true?

And yes we either need to change the default scopes in bigrquery, provide a helper function where we or user could more easily choose platform-appropriate scopes, or change the list of acceptable scopes for the GCE credential fetcher in gargle.

**Comment by htappen** [comment] 2020-06-07 02:04
Yes, using the command you sent works.

**Comment by jennybc** [comment] 2020-06-08 00:04
> Yes, using the command you sent works.

Great. So that gets you unstuck in the present while we determine the best way(s) to fix in the long-term.

**Comment by hadley** [comment] 2020-09-16 14:06
@jennybc do you think it's likely a fix will involve bigrquery, or is it more likely to happen in gargle?

**Comment by jennybc** [comment] 2020-09-16 14:54
Since I don't use BigQuery, I have a hard time judging what would happen if the default scopes for `bg_auth()` changed to just `"https://www.googleapis.com/auth/bigquery"`. But it's easy to imagine that creates as many headaches/issues as it solves? However that is extremely simple.

It is nice that there is already a way for a user to specify scopes, i.e. we have a reasonable workaround here.

I do have an issue about the question of whether scope checking could somehow come from the client package (https://github.com/r-lib/gargle/issues/25). Then each package could be responsible for its own special logic.

A general fix in gargle is not likely in the short-term.

**Comment by htappen** [comment] 2020-09-16 15:20
I'd suggest using option #2 from the ones I gave before (switch to .readonly scope in bq-auth). The compute engine scope is necessary for getting credentials from the local service account. It's a fairly simple change.

**Comment by jennybc** [comment] 2020-09-16 16:01
@craigcitro Do you have an opinion on changing the default scopes for `bq_auth()`? I believe the proposal is this:

```
https://www.googleapis.com/auth/bigquery       --> (leave unchanged)
https://www.googleapis.com/auth/cloud-platform --> cloud-platform.read-only
```

**Comment by craigcitro** [comment] 2020-09-17 23:45
Some thoughts/questions:

1. For BQ itself, either `bigquery` or `cloud-platform` is sufficient for all operations; this can be confirmed by inspecting [the discovery doc](https://www.googleapis.com/discovery/v1/apis/bigquery/v2/rest). So dropping `cloud-platform` seems fine.

1. @htappen can you say more about "necessary for getting credentials from the local service account"? Credentials aren't required for fetching a token from the GCE metadata server, but maybe you're saying that it's impossible to create a GCE VM with a service account without also having a GCE scope (hence `cloud-platform.readonly`)?

1. For users (especially users who already have a token with one of the scopes), it'd be nice to avoid having them do another auth dance due. (This is especially true if one day we end up switching the default scope to use back to `cloud-platform`.)

**Comment by htappen** [comment] 2020-09-19 16:30
(2) The most common way of authenticating from VMs on Google Compute Engine is to use a key assigned to the VM by GCE. To read that key and issue API calls, you need cloud-platform.readonly privileges IIRC.

**Comment by hadley** [comment] 2020-10-01 20:27
Dropping the `cloud-platform` scope or switching to `cloud-platform.read-only` leads to failures in tests:

```R
── Error (test-that.R:111:5): can roundtrip v
Error: Insufficient Permission [insufficientPermissions] 
Backtrace:
    █
 1. └─bigrquery:::gs_object_delete(gs)
 2.   └─bigrquery:::process_request(req)
 3.     └─bigrquery:::bq_check_response(status, type, content)
 4.       └─bigrquery:::signal_reason(json$error$errors[[1L]]$reason, json$error$message)
```

So given that changing the defaults seems risky, and there's already a way to override if needed, I'm going to close this issue.

**Closed by hadley** 2020-10-01 20:27 UTC
Labels: auth :key:, bug

**Comment by abalter** [comment] 2022-05-01 05:15
Hey, I've struggled mightily with authenticating `bigrquery` as well as other GCP R packages. Organizational policy prevents me from creating and downloading a service account key. In my desperate search today I stumbled across a solution in a separate `bigrquery` issue. [My comment here...](https://github.com/r-lib/gargle/issues/138).

@hadley, @jennybc --- would you be willing to consider providing more documentation help for authentication problems? Also maybe see if there are places the code could be made to function more seamlessly?

When we have problems with `bigrquery`, we end up having to follow murky trails through GCP authentication (and us users aren't the ones who set our scopes and permissions) as well as how gargle works in R. 

The fect that extremely simple "Step 2" in the referenced issue so seamlessly solved the problem for me and others suggests that perhaps the R gargle could know where to look for the `adc.json` file without having to move it?

**Comment by hadley** [comment] 2022-05-01 13:33
@abalter instead of filing on a old, closed, issue, please create a new issue that summarise all of the details in one place.

**Comment by abalter** [comment] 2022-05-01 17:39
@hadley -- will do! Would it be correct to say that the issue is with bigquery authentication, or that gargle isn't looking in the right place for the auth file? Should I file the issue with [gargle](https://github.com/r-lib/gargle)?
