### ISSUE TITLE
Cross Projects Queries & Joins

### ISSUE THREAD

**Issue by tchaithonov** [r-dbi/bigrquery#394] opened 2020-07-20 19:50 UTC
Hi All,

I wonder if bigrquery can join tables from two different big query projects.  I can do that in SQL, but I want to be able to document it via RMarkdown (but failed).  Say I want to do a join between tableA from project One, and tableB from project Two:

```sql
select * from `project_one.dataset1.tableA` a
inner join 'project_two.dataset1.tableB` b
using (colC);
```

This works well in the BigQuery interface (and if I run this as a SQL chuck in RMarkdown), but it comes back with an error when I run this in R:
```r
Error in UseMethod("copy_to") : 
  no applicable method for 'copy_to' applied to an object of class "c('tbl_BigQueryConnection', 'tbl_dbi', 'tbl_sql', 'tbl_lazy', 'tbl')"
```

Is there a way I can do it?  Please let me know.  Thanks.

**Comment by hadley** [comment] 2020-09-16 14:02
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment] 2020-10-01 19:58
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2020-10-01 19:58 UTC
Labels: reprex
