### ISSUE TITLE
Error in insert_upload_job "Stream error in the HTTP/2 framing layer"

### ISSUE THREAD

**Issue by selesnow** [r-dbi/bigrquery#170] opened 2017-07-21 10:37 UTC
Hi!
When i run insert_upload_job with in data frame who contains more than 70 rows i get error:

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Stream error in the HTTP/2 framing layer

When i send small data frame (less 20 rows) function work correctly.

Now i can send big data frame by breaking them into parts, but this way greatly increases the load time of data into BigQuery.

Сan you help in this issure?

SessionInfo
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2008 R2 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bigrquery_0.4.1

loaded via a namespace (and not attached):
[1] httr_1.2.1       compiler_3.4.1   R6_2.2.2         assertthat_0.2.0
[5] DBI_0.7          tools_3.4.1      curl_2.7         jsonlite_1.5    
[9] openssl_0.9.6

**Comment by TerryZhangHL** [comment] 2017-08-28 19:22
any luck with this issue?

**Comment by hadley** [comment] 2018-03-28 22:08
Duplicate of #165; will be fixed by updating curl package.

**Closed by hadley** 2018-03-28 22:08 UTC
