### ISSUE TITLE
Can't auth with httr.oauth

### ISSUE THREAD

**Issue by zkostitsyn** [r-dbi/bigrquery#214] opened 2018-03-26 09:39 UTC
When I run function "insert_upload_job" I get error:
`Auto-refreshing stale OAuth token.
Error in gzfile(file, mode) : cannot open the connection
In addition: Warning message:
In gzfile(file, mode) :
  cannot open compressed file '.httr-oauth', probable reason 'Permission denied'`

It only happens the first time you run function. In the second time it runs correctly
Because of this error, I cannot use the task scheduler
I have read a lot of topics about similar problems with httr.oauth, but has not yet been able to solve the problem

**Comment by hadley** [comment] 2018-03-28 22:25
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment] 2018-04-03 21:24
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2018-04-03 21:24 UTC
Labels: reprex
