### ISSUE TITLE
Error: invalid_request for get_access_cred()

### ISSUE THREAD

**Issue by alex-danilin** [r-dbi/bigrquery#182] opened 2017-08-17 13:58 UTC
Hi.

When I'm trying to use get_access_cred() (or just run query_exec() first time in session) I get this from Google:
**400**. That’s an error.
**Error: invalid_request**
Missing required parameter: redirect_uri
Learn more
Request Details
That’s all we know.

**sessionInfo()**
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251   
[3] LC_MONETARY=Russian_Russia.1251 LC_NUMERIC=C                   
[5] LC_TIME=Russian_Russia.1251    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.7.2        purrr_0.2.3        readr_1.1.1        tidyr_0.7.0       
[5] tibble_1.3.3       ggplot2_2.2.1.9000 tidyverse_1.1.1    bigrquery_0.4.1   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12     cellranger_1.1.0 compiler_3.4.1   plyr_1.8.4       bindr_0.1       
 [6] forcats_0.2.0    tools_3.4.1      lubridate_1.6.0  jsonlite_1.5     nlme_3.1-131    
[11] gtable_0.2.0     lattice_0.20-35  pkgconfig_2.0.1  rlang_0.1.2      psych_1.7.5     
[16] DBI_0.7          curl_2.8.1       parallel_3.4.1   haven_1.1.0      bindrcpp_0.2    
[21] xml2_1.1.1       httr_1.3.0       stringr_1.2.0    hms_0.3          grid_3.4.1      
[26] glue_1.1.1       R6_2.2.2         readxl_1.0.0     foreign_0.8-69   modelr_0.1.1    
[31] reshape2_1.4.2   magrittr_1.5     scales_0.4.1     rvest_0.3.2      assertthat_0.2.0
[36] mnormt_1.5-5     colorspace_1.3-2 httpuv_1.3.5     stringi_1.1.5    lazyeval_0.2.0  
[41] munsell_0.4.3    broom_0.4.2

**Comment by EricGoldsmith** [comment] 2017-08-17 17:56
I ran across this today, too. It seems the cause is an incompatibility with the newly released (yesterday) httr v1.3.0. Reverting to the prior version, via `devtools::install_version("httr", version = "1.2.1")` resolved the issue for me.

**Comment by alex-danilin** [comment] 2017-08-18 09:59
It is possible to solve this problem using
set_service_token('path_to_service_token.json')
or
options("httr_oob_default" = TRUE)
but this is more like workarounds.

**Comment by EricGoldsmith** [comment] 2017-08-25 15:25
This issue seems to be resolved with [httr v1.3.1](https://github.com/r-lib/httr/releases/tag/v1.3.1)

**Comment by alex-danilin** [comment] 2017-08-29 13:22
Yes, it seems like everything is ok after updating httr to 1.3.1.

**Comment by juliasilge** [comment] 2017-10-25 04:42
I am getting this error with httr 1.3.1 as well. I can run `query_exec()` for the first time successfully after downgrading back to httr 1.2.1.

**Comment by EricGoldsmith** [comment] 2017-10-25 14:20
Oddly, I'm not having this problem with httr 1.3.1 - and haven't since upgrading to it. Here's my session info, in case it provides some clues.

<details><summary>Session Info</summary><p>

```
> devtools::session_info()
Session info ---------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2017-10-25                  

Packages -------------------------------------------------------------------------------------------------------------------------------------
 package     * version date       source                       
 assertthat    0.2.0   2017-04-11 CRAN (R 3.4.0)               
 base        * 3.4.2   2017-10-04 local                        
 bigrquery   * 0.4.1   2017-06-26 CRAN (R 3.4.1)               
 bindr         0.1     2016-11-13 CRAN (R 3.4.0)               
 bindrcpp    * 0.2     2017-06-17 CRAN (R 3.4.0)               
 colorspace    1.3-2   2016-12-14 CRAN (R 3.4.0)               
 compiler      3.4.2   2017-10-04 local                        
 curl          3.0     2017-10-06 CRAN (R 3.4.2)               
 datasets    * 3.4.2   2017-10-04 local                        
 DBI           0.7     2017-06-18 CRAN (R 3.4.0)               
 devtools      1.13.3  2017-08-02 CRAN (R 3.4.1)               
 digest        0.6.12  2017-01-27 CRAN (R 3.4.0)               
 dplyr       * 0.7.4   2017-09-28 CRAN (R 3.4.2)               
 ggplot2     * 2.2.1   2016-12-30 CRAN (R 3.4.0)               
 glue          1.1.1   2017-06-21 CRAN (R 3.4.1)               
 graphics    * 3.4.2   2017-10-04 local                        
 grDevices   * 3.4.2   2017-10-04 local                        
 grid          3.4.2   2017-10-04 local                        
 gtable        0.2.0   2016-02-26 CRAN (R 3.4.0)               
 httr          1.3.1   2017-08-20 CRAN (R 3.4.1)               
 jsonlite      1.5     2017-06-01 CRAN (R 3.4.0)               
 lazyeval      0.2.0   2016-06-12 CRAN (R 3.4.0)               
 lubridate   * 1.6.0   2016-09-13 CRAN (R 3.4.0)               
 magrittr      1.5     2014-11-22 CRAN (R 3.4.0)               
 memoise       1.1.0   2017-04-21 CRAN (R 3.4.0)               
 methods     * 3.4.2   2017-10-04 local                        
 munsell       0.4.3   2016-02-13 CRAN (R 3.4.0)               
 openssl       0.9.7   2017-09-06 CRAN (R 3.4.1)               
 pkgconfig     2.0.1   2017-03-21 CRAN (R 3.4.0)               
 plyr          1.8.4   2016-06-08 CRAN (R 3.4.0)               
 prettyunits   1.0.2   2015-07-13 CRAN (R 3.4.0)               
 progress      1.1.2   2016-12-14 CRAN (R 3.4.0)               
 purrr         0.2.3   2017-08-02 CRAN (R 3.4.1)               
 R6            2.2.2   2017-06-17 CRAN (R 3.4.0)               
 Rcpp          0.12.13 2017-09-28 CRAN (R 3.4.2)               
 rlang         0.1.2   2017-08-09 CRAN (R 3.4.1)               
 rted        * 0.4.1   2017-09-21 Github (tedconf/rted@7b81e4c)
 scales      * 0.5.0   2017-08-24 CRAN (R 3.4.1)               
 stats       * 3.4.2   2017-10-04 local                        
 stringi       1.1.5   2017-04-07 CRAN (R 3.4.0)               
 stringr       1.2.0   2017-02-18 CRAN (R 3.4.0)               
 tibble        1.3.4   2017-08-22 CRAN (R 3.4.1)               
 tidyr         0.7.2   2017-10-16 CRAN (R 3.4.2)               
 tidyselect    0.2.2   2017-10-10 CRAN (R 3.4.2)               
 tools         3.4.2   2017-10-04 local                        
 utils       * 3.4.2   2017-10-04 local                        
 withr         2.0.0   2017-07-28 CRAN (R 3.4.1)               
 yaml          2.1.14  2016-11-12 CRAN (R 3.4.0)
```


</p></details>

**Comment by EricGoldsmith** [comment] 2017-11-07 00:11
I saw this error again today, and it was a case where there was not an existing cached token (e.g. no `.httr-oauth` file). 

To work around, I set this option `options("httr_oob_default" = TRUE)` and used the OOB auth method to create and cache the token. 

So, it appears that this issue *does* still exist. 

@alex-danilin, can you confirm and re-open the issue? Just delete any existing `.httr-oauth` file and try a BQ `query_exec()`.

**Comment by alex-danilin** [comment] 2017-11-07 08:14
@EricGoldsmith Yes, the error is back with no .httr-oauth file.

**Comment by chrishaid** [comment] 2017-11-17 16:23
I can verify that this issue is back.  I can recreate with @alex-danilin steps: delete the `.httr-oath` file and run any `bigrquery` command that needs to talk to BQ. 

The `options("httr_oob_default" = TRUE)` setting works to get around this issue.

**Comment by koaning** [comment] 2018-01-29 19:52
I just installed everything anew today and ran into the same error again.

**Comment by hadley** [comment] 2018-03-28 22:14
Could someone please make reproducible example using the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by j450h1** [comment] 2018-03-31 06:08
The full reprex doesn't work so I had to comment out the main function. I think its perhaps because because the function get_access_cred() is interactive as it initially requests user input. Nonetheless, hopefully this helps. 

* First, delete any existing .httr-oauth file in working directory

``` r
library(bigrquery)
sessionInfo()
#> R version 3.4.4 (2018-03-15)
#> Platform: x86_64-apple-darwin15.6.0 (64-bit)
#> Running under: macOS High Sierra 10.13.3
#> 
#> Matrix products: default
#> BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] bigrquery_0.4.1
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_0.12.16     digest_0.6.15    rprojroot_1.3-2  assertthat_0.2.0
#>  [5] R6_2.2.2         DBI_0.8          backports_1.1.2  magrittr_1.5    
#>  [9] evaluate_0.10.1  httr_1.3.1       stringi_1.1.7    rmarkdown_1.9   
#> [13] tools_3.4.4      stringr_1.3.0    yaml_2.1.18      compiler_3.4.4  
#> [17] htmltools_0.3.6  knitr_1.20
#get_access_cred()

#### This is what displays in the console - when I uncomment the function: ###
# get_access_cred()
# Use a local file ('.httr-oauth'), to cache OAuth access credentials between R sessions?
#   
# 1: Yes
# 2: No
```

Created on 2018-03-30 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

* Entering either 1 or 2 opens up a browser window and this same error:

[![Screen_Shot_2018-03-30_at_11.02.38_PM.png](https://s9.postimg.org/hnhnd871b/Screen_Shot_2018-03-30_at_11.02.38_PM.png)](https://postimg.org/image/wjg6ktifv/)

**Comment by j450h1** [comment] 2018-03-31 06:21
And of course, adding the 1 options line takes you to the correct link:
```
library(bigrquery)
sessionInfo()
options("httr_oob_default" = TRUE)
get_access_cred()
```
You now see something like this:

[![Screen_Shot_2018-03-30_at_11.18.59_PM.png](https://s9.postimg.org/cemmfayvz/Screen_Shot_2018-03-30_at_11.18.59_PM.png)](https://postimg.org/image/l9ngptnob/)

**Comment by hadley** [comment] 2018-04-03 21:34
I think this is fixed in the development version. I could reproduce with the version I had installed, but once I reinstalled the development version, the problem went away.

If that doesn't work for you, please file a new issue containing the result of running this code

```R
library(bigrquery)

unlink(".httr-oauth")
reset_access_cred()
httr::with_verbose(get_access_cred())
```

__and__ the full url of the google site that opens in your browser. Please do not include session info.

**Closed by hadley** 2018-04-03 21:34 UTC
Labels: reprex
