### ISSUE TITLE
? could you check, please

### ISSUE THREAD

**Issue by VictArt** [r-dbi/bigrquery#200] opened 2018-02-23 15:34 UTC
https://github.com/r-dbi/bigrquery/blob/192d9423cd6a01d064e9320db3e57658b3262ed0/R/tables.r#L184

**Comment by VictArt** [comment] 2018-02-23 15:40
bq_post(url, body = bq_body(body, ...)) - copy_table works well with this

**Comment by byapparov** [comment] 2018-03-04 22:58
It is a bug. can you make a PR?

**Comment by byapparov** [comment] 2018-03-06 13:16
I need it fixed my self, here is the PR#208

**Comment by hadley** [comment] 2018-03-28 22:10
Duplicate of #172

**Closed by hadley** 2018-03-28 22:10 UTC
